[project]
name = "textcrawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.8.0",
    "pydantic>=2.12.5",
    "dotenv>=0.9.9",
    "asyncio>=4.0.0"
]
